import type { Metadata } from "next";
import Header from "@/app/ui/header";
import "./globals.css";
import { geistSans, geistMono } from "@/app/ui/fonts";

export const metadata: Metadata = {
  title: "Lorenzio's Pizza",
  description: "Generated by create next app",
};

export const experimental_ppr = true;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col pt-[62px] md:pt-[82px]`}
      >
        <Header />
        <main className="flex-1 flex flex-col">
          {children}
        </main>
      </body>
    </html>
  );
}
